version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html  # Mount current directory to /var/www/html inside the container
    working_dir: /var/www/html  # Set working directory to /var/www/html
    ports:
      - "8711:80"
    networks:
      - php-network

networks:
  php-network:
    driver: bridge